const assert = require('node:assert/strict')
const { createServer } = require('node:http')
const fs = require('node:fs/promises')
const path = require('node:path')
const { chromium } = require('playwright')

const root = path.resolve('.dsh-showcase/site')
const mime = { '.html': 'text/html; charset=utf-8', '.js': 'text/javascript; charset=utf-8', '.css': 'text/css; charset=utf-8', '.json': 'application/json', '.png': 'image/png' }
const server = createServer(async (request, response) => {
  const route = new URL(request.url, 'http://localhost').pathname
  if (route === '/frame') {
    response.setHeader('Content-Type', 'text/html')
    response.end('<!doctype html><html><body style="margin:0"><iframe title="Space" src="/index.html" style="border:0;width:100vw;height:100vh"></iframe></body></html>')
    return
  }
  const file = path.resolve(root, `.${route === '/' ? '/index.html' : route}`)
  if (!file.startsWith(root + path.sep)) { response.writeHead(403).end(); return }
  try { response.setHeader('Content-Type', mime[path.extname(file)] || 'text/plain'); response.end(await fs.readFile(file)) }
  catch { response.writeHead(404).end() }
})

;(async () => {
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve))
  const origin = `http://127.0.0.1:${server.address().port}`
  const browser = await chromium.launch({ headless: true })
  const errors = []
  try {
    await fs.mkdir('.dsh-showcase/screenshots', { recursive: true })
    for (const width of [1440, 390, 320]) {
      const context = await browser.newContext({ viewport: { width, height: 1000 }, reducedMotion: 'reduce' })
      await context.addInitScript(() => {
        Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: async () => { throw new Error('Clipboard denied by embed') } } })
      })
      const page = await context.newPage()
      page.on('pageerror', error => errors.push(String(error)))
      const requests = []
      page.on('request', request => requests.push(request.url()))
      await page.goto(`${origin}/frame`)
      const frame = page.frameLocator('iframe')
      await frame.locator('[data-name="review"]').waitFor()
      assert.equal(await frame.locator('.skill-row').count(), 8)
      assert.equal(await frame.locator('#listed-count').innerText(), '3')
      assert(await frame.getByRole('button', { name: 'Inspect manual-deploy', exact: true }).isDisabled())
      const inner = page.frames().find(item => item.url().includes('/index.html'))
      assert.equal(await inner.evaluate(() => document.documentElement.scrollWidth > innerWidth), false)
      assert.equal(await frame.locator('[data-scenario="default"]').getAttribute('aria-pressed'), 'true')
      await frame.getByRole('button', { name: 'Inspect review', exact: true }).click()
      assert.equal(await inner.evaluate(() => document.activeElement.id), 'selected-name')
      await page.keyboard.press('Tab')
      assert.equal(await inner.evaluate(() => document.activeElement.id), 'back-to-skills')
      await page.keyboard.press('Enter')
      assert.equal(await inner.evaluate(() => document.activeElement.getAttribute('aria-label')), 'Inspect review')
      await frame.locator('#search').fill('zzzznotfoundzzzz')
      assert.equal(await frame.locator('.skill-row').count(), 0)
      await frame.locator('#back-to-skills').click()
      assert.equal(await inner.evaluate(() => document.activeElement.id), 'search')
      await frame.locator('#clear-search').click()
      assert.equal(await inner.evaluate(() => document.activeElement.id), 'search')
      assert.equal(await frame.locator('.skill-row').count(), 8)
      await frame.locator('#robot-start').click()
      assert.equal(await inner.evaluate(() => document.activeElement.id), 'workspace-title')
      assert.equal(await frame.locator('#selected-name').innerText(), 'robot-reel-review')
      assert(await frame.locator('#review-workflow').isVisible())
      await frame.getByRole('button', { name: 'Reset workspace' }).click()
      await frame.getByRole('button', { name: '03 Find a hidden skill' }).click()
      assert.equal(await frame.locator('#selected-name').innerText(), 'test-plan')
      assert.equal(await frame.locator('#selected-state').innerText(), 'on demand')
      await frame.getByRole('button', { name: 'Pin test-plan', exact: true }).click()
      assert.equal(await frame.locator('#selected-state').innerText(), 'in catalog')
      assert.equal(await frame.locator('[data-scenario][aria-pressed="true"]').count(), 0)
      assert.match(await frame.locator('#scenario-note').innerText(), /^Custom view/)
      await frame.getByRole('button', { name: 'Hide test-plan', exact: true }).click()
      assert.equal(await frame.locator('#selected-state').innerText(), 'on demand')
      assert.equal(await frame.locator('[data-name="test-plan"]').count(), 1)
      await frame.getByRole('button', { name: 'Copy this view', exact: true }).click()
      const shared = await frame.locator('#share-fallback').inputValue()
      assert.match(shared, /budget=1/)
      assert.match(shared, /pin=test-plan/)
      await inner.goto(shared)
      await inner.evaluate(() => location.reload())
      await frame.locator('#scenario-note').filter({ hasText: 'Restored view' }).waitFor()
      await frame.locator('[data-name="test-plan"]').waitFor()
      assert.equal(await frame.locator('[data-scenario][aria-pressed="true"]').count(), 0)
      assert.match(await frame.locator('#scenario-note').innerText(), /^Restored view/)
      assert.equal(await frame.locator('#selected-state').innerText(), 'on demand')
      assert.equal(await frame.getByRole('button', { name: 'Hide test-plan', exact: true }).getAttribute('aria-pressed'), 'true')
      const download = page.waitForEvent('download')
      await frame.getByRole('button', { name: 'Download sample workspace', exact: true }).click()
      const received = await download
      const exported = JSON.parse(await fs.readFile(await received.path(), 'utf8'))
      assert.equal(exported.files.length, 10)
      assert.equal(exported.schema, 'skills-anywhere-playground-1')
      await frame.getByRole('button', { name: '04 Review robot evidence' }).click()
      assert.equal(await frame.locator('#selected-name').innerText(), 'robot-reel-review')
      assert.equal(await frame.locator('.skill-row').count(), 1)
      assert(await frame.locator('#review-workflow').isVisible())
      assert.match(await frame.locator('#selected-content').innerText(), /--verify --frame-json/)
      const robotShare = page.waitForEvent('download')
      await frame.getByRole('button', { name: 'Download sample workspace', exact: true }).click()
      const robotFiles = JSON.parse(await fs.readFile(await (await robotShare).path(), 'utf8')).files
      assert.equal(robotFiles.find(file => file.path.endsWith('/robot-reel-review/SKILL.md')).markdown,
        await fs.readFile('examples/robot-reel-review/SKILL.md', 'utf8'))
      await frame.getByRole('button', { name: '02 Untangle a name clash' }).click()
      assert.equal(await frame.locator('.skill-row').count(), 2)
      await frame.locator('#search').fill('manual-deploy')
      assert.equal(await frame.locator('.skill-row').count(), 0)
      await frame.locator('#search').fill('<img src=x onerror=alert(1)>')
      assert.equal(await frame.locator('.skill-row').count(), 0)
      const catalog = await frame.locator('#listed-count').innerText()
      await frame.locator('#clear-search').click()
      assert.equal(await frame.locator('#listed-count').innerText(), catalog)
      assert.equal(await frame.locator('#search').inputValue(), '')
      await frame.getByRole('button', { name: 'Reset workspace' }).click()
      await frame.getByRole('tab', { name: 'Explore CLI', exact: true }).focus()
      await page.keyboard.press('ArrowRight')
      assert.match(await frame.locator('#install-command').innerText(), /^dsh plugin/)
      await frame.getByRole('tab', { name: 'MCP clients', exact: true }).click()
      assert.match(await frame.locator('#install-command').innerText(), / mcp$/)
      await frame.locator('#budget').focus()
      await page.keyboard.press('Home')
      assert.equal(await frame.locator('#listed-count').innerText(), '7')
      await frame.getByRole('button', { name: 'Reset workspace' }).click()
      await frame.getByRole('button', { name: 'Load repair example', exact: true }).click()
      assert.equal(await frame.locator('#check-strict-state').innerText(), 'Rejected')
      assert.equal(await frame.locator('#check-lenient-state').innerText(), 'Accepted with repairs')
      assert.match(await frame.locator('#check-lenient-details').innerText(), /incident-summary/)
      const markdown = '---\nname: private-skill\ndescription: A local check.\ndisable-model-invocation: true\n---\nLOCAL_ONLY_SENTINEL <img src=x onerror=alert(1)>'
      await frame.locator('#check-input').fill(markdown)
      assert(await frame.getByRole('button', { name: 'Download check report', exact: true }).isDisabled())
      await frame.getByRole('button', { name: 'Check SKILL.md', exact: true }).click()
      assert.match(await frame.locator('#check-strict-details').innerText(), /author disabled/)
      assert(!(await inner.evaluate(() => location.hash)).includes('LOCAL_ONLY'))
      const reportDownload = page.waitForEvent('download')
      await frame.getByRole('button', { name: 'Download check report', exact: true }).click()
      const reportText = await fs.readFile(await (await reportDownload).path(), 'utf8')
      assert.equal(JSON.parse(reportText).strict.name, 'private-skill')
      assert(!reportText.includes('LOCAL_ONLY_SENTINEL'))
      await frame.locator('#check-input').fill([
        '---', 'name: source-review', 'description: Review external instructions.',
        'allowed-tools: Read WebFetch', '---',
        `https://raw.githubusercontent.com/team/repo/${'a'.repeat(40)}/SKILL.md`,
        `https://example.com/instructions#sha256:${'b'.repeat(64)}`,
      ].join('\n'))
      await frame.locator('#check-run').click()
      assert.match(await frame.locator('#check-source-state').innerText(), /2 hosts · 1 need source review/)
      assert.match(await frame.locator('#check-sources').innerText(), /Full-commit addresses/)
      assert.match(await frame.locator('#check-sources').innerText(), /Unverified or mutable address/)
      assert.equal(await frame.locator('#check-tools').innerText(), 'Read\nWebFetch')
      assert.equal(await frame.locator('#check-sources a').count(), 0)
      assert(await inner.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1))
      await frame.locator('#check-input').fill('---\nname: [invalid yaml\n---')
      await frame.locator('#check-run').click()
      assert.match(await frame.locator('#check-source-state').innerText(), /Unavailable/)
      assert.equal(await frame.locator('#check-sources li').count(), 0)
      await frame.locator('#check-file').setInputFiles({ name: 'SKILL.md', mimeType: 'text/markdown', buffer: Buffer.from(markdown) })
      await frame.locator('#check-status').filter({ hasText: 'Checked' }).waitFor()
      assert.equal(await frame.locator('#check-strict-state').innerText(), 'Accepted')
      await frame.locator('#check-file').setInputFiles({ name: 'large.md', mimeType: 'text/plain', buffer: Buffer.alloc(128 * 1024 + 1, 'a') })
      await frame.locator('#check-status').filter({ hasText: '128 KiB' }).waitFor()
      assert(await frame.getByRole('button', { name: 'Download check report', exact: true }).isDisabled())
      await frame.locator('#check-file').setInputFiles({ name: 'invalid.md', mimeType: 'text/plain', buffer: Buffer.from([0xff]) })
      await frame.locator('#check-status').filter({ hasText: 'UTF-8' }).waitFor()
      assert.equal(await frame.locator('#check').getAttribute('aria-busy'), 'false')
      assert(await frame.locator('#check-run').isEnabled())
      await frame.locator('#bundle-verdict').filter({ hasText: 'REVIEW REQUIRED' }).waitFor()
      assert.equal(await frame.locator('#bundle-skill-state').innerText(), 'SKILL.md is unchanged.')
      assert.match(await frame.locator('#bundle-changes').innerText(), /CHANGED  scripts\/review.py/)
      const beforeDownload = page.waitForEvent('download')
      await frame.locator('#bundle-download-reviewed').click()
      const reviewed = JSON.parse(await fs.readFile(await (await beforeDownload).path(), 'utf8'))
      const afterDownload = page.waitForEvent('download')
      await frame.locator('#bundle-download-current').click()
      const current = JSON.parse(await fs.readFile(await (await afterDownload).path(), 'utf8'))
      assert.notEqual(reviewed.sha256, current.sha256)
      assert.deepEqual(reviewed.files.find(f => f.path === 'SKILL.md'), current.files.find(f => f.path === 'SKILL.md'))
      await frame.locator('#bundle-demo-matching').click()
      await frame.locator('#bundle-verdict').filter({ hasText: /^MATCH$/ }).waitFor()
      await frame.locator('#bundle-file-current').setInputFiles({ name: 'LOCAL_BUNDLE.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(current)) })
      await frame.locator('#bundle-verdict').filter({ hasText: 'REVIEW REQUIRED' }).waitFor()
      assert(!(await inner.evaluate(() => location.hash)).includes('LOCAL_BUNDLE'))
      await frame.locator('#bundle-file-current').setInputFiles({ name: 'forged.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify({ ...current, sha256: '0'.repeat(64) })) })
      await frame.locator('#bundle-status').filter({ hasText: 'disagrees' }).waitFor()
      assert(await frame.locator('#bundle-results').isHidden())
      assert(await frame.locator('#bundle-download-current').isDisabled())
      await frame.locator('#bundle-file-current').setInputFiles({ name: 'large.json', mimeType: 'application/json', buffer: Buffer.alloc(1024 * 1024 + 1) })
      await frame.locator('#bundle-status').filter({ hasText: '1 MiB' }).waitFor()
      await inner.evaluate(() => {
        const original = File.prototype.arrayBuffer
        window.restoreBundleReader = () => { File.prototype.arrayBuffer = original }
        File.prototype.arrayBuffer = function () {
          return new Promise(resolve => { window.finishBundleRead = () => original.call(this).then(resolve) })
        }
      })
      await frame.locator('#bundle-file-current').setInputFiles({ name: 'slow.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(current)) })
      await frame.locator('#bundle-demo-matching').click()
      await frame.locator('#bundle-verdict').filter({ hasText: /^MATCH$/ }).waitFor()
      await inner.evaluate(async () => { await window.finishBundleRead(); window.restoreBundleReader(); await new Promise(resolve => setTimeout(resolve, 0)) })
      assert.equal(await frame.locator('#bundle-verdict').innerText(), 'MATCH')
      assert.equal(await frame.locator('html').evaluate(element => element.scrollWidth <= innerWidth), true)
      await frame.locator('#bundle-demo-changed').click()
      await frame.locator('#bundle-verdict').filter({ hasText: 'REVIEW REQUIRED' }).waitFor()
      await inner.evaluate(() => {
        const original = File.prototype.arrayBuffer
        File.prototype.arrayBuffer = function () {
          return new Promise(resolve => { window.finishOldRead = () => original.call(this).then(resolve) })
        }
      })
      await frame.locator('#check-file').setInputFiles({ name: 'slow.md', mimeType: 'text/markdown', buffer: Buffer.from(markdown) })
      assert.equal(await frame.locator('#check').getAttribute('aria-busy'), 'true')
      assert(await frame.locator('#check-run').isDisabled())
      await frame.getByRole('button', { name: 'Clear local input', exact: true }).click()
      await inner.evaluate(async () => { await window.finishOldRead(); await new Promise(resolve => setTimeout(resolve, 0)) })
      assert.equal(await frame.locator('#check-input').inputValue(), '')
      assert(await frame.locator('#check-results').isHidden())
      assert.equal(await frame.locator('#check').getAttribute('aria-busy'), 'false')
      assert(requests.every(url => url.startsWith(origin) || url.startsWith('blob:')), 'Unexpected external request')
      await fs.mkdir('.dsh-showcase/screenshots', { recursive: true })
      await page.screenshot({ path: `.dsh-showcase/screenshots/embed-${width}.png`, fullPage: true })
      await context.close()
    }
    const page = await browser.newPage({ viewport: { width: 1600, height: 1000 }, deviceScaleFactor: 1 })
    page.on('pageerror', error => errors.push(String(error)))
    await page.goto(`${origin}/`)
    await page.locator('[data-name="review"]').waitFor()
    await page.screenshot({ path: path.join(root, 'thumbnail.png') })
    await page.goto(`file://${path.join(root, 'index.html')}`)
    await page.locator('[data-name="review"]').waitFor()
    await page.locator('#bundle-verdict').filter({ hasText: 'REVIEW REQUIRED' }).waitFor()
    await page.getByRole('button', { name: '02 Untangle a name clash' }).click()
    assert.equal(await page.locator('.skill-row').count(), 2)
    await page.getByRole('button', { name: 'Load repair example', exact: true }).click()
    assert.equal(await page.locator('#check-lenient-state').innerText(), 'Accepted with repairs')
    await page.getByRole('button', { name: '04 Review robot evidence' }).click()
    assert.equal(await page.locator('#selected-name').innerText(), 'robot-reel-review')
    for (const width of [1440, 390, 320]) {
      await page.setViewportSize({ width, height: 2400 })
      await page.locator('#bundle').screenshot({ path: `.dsh-showcase/screenshots/bundle-${width}.png` })
    }
    assert.deepEqual(errors, [])
    console.log('Showcase browser checks passed: desktop/mobile iframe, source fixture, budget/search, disabled skills, share fallback, download, keyboard tabs, offline.')
  } finally {
    await browser.close()
    await new Promise(resolve => server.close(resolve))
  }
})().catch(error => { console.error(error); server.close(); process.exitCode = 1 })
